### ISSUE TITLE
Groups ID 如何获取

### ISSUE THREAD

**Issue by GloryBoy239** [clatteringmarion/GDAutoAdd#2]
用drive ID 能够正常加盘。但是GROUPS ID是什么，群组邮箱么？（我使用群组邮箱，没有报错，但是显示成功后，群组里却没有这个账号）这个怎么获取？求大佬指点

**Comment by clatteringmarion** [comment]
Group ID就是群组邮箱啊。 但是使用群组那个需要Google GSuite或者Workspace群组 + SA账户（需要开Admin那个API）。
这个功能使用比较少所以文档也不怎么完善… 抱歉啦

另外， 没想到现在还有人在用这个代码😂

**Comment by CNBOY239** [comment]
> Group ID就是群组邮箱啊。 但是使用群组那个需要Google GSuite或者Workspace群组 + SA账户（需要开Admin那个API）。
> 这个功能使用比较少所以文档也不怎么完善… 抱歉啦
> 
> 另外， 没想到现在还有人在用这个代码😂

可能问题就在这。我使用的是个人账户建的群组；另外也么配置SA。

这么久了还在用。只能说我是小白，哈哈哈。另外，大佬的东西也是经得时间考验的。

我用团队盘ID是成功了。只是考虑如果把盘放出去到时候MJJ们一通加，用户管理就麻烦了。如果能配置群组，那直接加群组里，看起来也干净，管理也方便

**Comment by clatteringmarion** [comment]
嗯， 我等什么时候写新的跟Worker KV配套使用的时候把文档也加上吧
没准再搞个i18n

最近太懒了。

**Comment by clatteringmarion** [comment]
文档已经加上了， issue关闭
